#pragma once

enum class Tile
{
	Unused,
	Wall,
	Ground,
	GroundOrangeLava,
	GroundRedLava,

	HeroBottomFirstFrame = 0,
	HeroBottomSecondFrame,
	HeroBottomThirdFrame,
	SpiderBottomFirstFrame,
	SpiderBottomSecondFrame,
	SpiderBottomThirdFrame,
	SkeletonBottomFirstFrame,
	SkeletonBottomSecondFrame,
	SkeletonBottomThirdFrame,

	HeroLeftFirstFrame,
	HeroLeftSecondFrame,
	HeroLeftThirdFrame,
	SpiderLeftFirstFrame,
	SpiderLeftSecondFrame,
	SpiderLeftThirdFrame,
	SkeletonLeftFirstFrame,
	SkeletonLeftSecondFrame,
	SkeletonLeftThirdFrame,

	HeroRightFirstFrame,
	HeroRightSecondFrame,
	HeroRightThirdFrame,
	SpiderRightFirstFrame,
	SpiderRightSecondFrame,
	SpiderRightThirdFrame,
	SkeletonRightFirstFrame,
	SkeletonRightSecondFrame,
	SkeletonRightThirdFrame,

	HeroTopFirstFrame,
	HeroTopSecondFrame,
	HeroTopThirdFrame,
	SpiderTopFirstFrame,
	SpiderTopSecondFrame,
	SpiderTopThirdFrame,
	SkeletonTopFirstFrame,
	SkeletonTopSecondFrame,
	SkeletonTopThirdFrame,

	SlimeBottomFirstFrame,
	SlimeBottomSecondFrame,
	SlimeBottomThirdFrame,
	BatBottomFirstFrame,
	BatBottomSecondFrame,
	BatBottomThirdFrame,
	GhostBottomFirstFrame,
	GhostBottomSecondFrame,
	GhostBottomThirdFrame,

	SlimeLeftFirstFrame,
	SlimeLeftSecondFrame,
	SlimeLeftThirdFrame,
	BatLeftFirstFrame,
	BatLeftSecondFrame,
	BatLeftThirdFrame,
	GhostLeftFirstFrame,
	GhostLeftSecondFrame,
	GhostLeftThirdFrame,

	SlimeRightFirstFrame,
	SlimeRightSecondFrame,
	SlimeRightThirdFrame,
	BatRightFirstFrame,
	BatRightSecondFrame,
	BatRightThirdFrame,
	GhostRightFirstFrame,
	GhostRightSecondFrame,
	GhostRightThirdFrame,

	SlimeTopFirstFrame,
	SlimeTopSecondFrame,
	SlimeTopThirdFrame,
	BatTopFirstFrame,
	BatTopSecondFrame,
	BatTopThirdFrame,
	GhostTopFirstFrame,
	GhostTopSecondFrame,
	GhostTopThirdFrame,


};
